package config

const (
	COUNTRY_CODE_MAX = 298

	LISTING_IMAGES_MAX_COUNT       = 3
	LISTING_CATEGORIES_MAX_COUNT   = 2
	LISTING_SHIPPING_TO_MAX_COUNT  = 20
	LISTING_DESCRIPTION_MAX_LENGTH = 3 * 1024
	LISTING_TITLE_MAX_LENGTH       = 255
	LISTING_TITLE_MIN_LENGTH       = 8
	LISTING_OFFER_MIN_LENGTH       = 2
	LISTING_OFFER_MAX_LENGTH       = 60
	LISTING_SHIPPING_MIN_LENGTH    = 2
	LISTING_SHIPPING_MAX_LENGTH    = 30
	LISTING_IMAGE_MAX_LENGTH       = 255
	LISTING_OFFERS_MAX_COUNT       = 10
	LISTING_SHIPPING_MAX_COUNT     = 10
	LISTINGS_LIST_COUNT            = 10
	INVOICE_DELIVERY_MIN_LENGTH    = 3
	INVOICE_DELIVERY_MAX_LENGTH    = 512
	INVOICE_NOTES_MAX_LENGTH       = 512
)
