package config

const (
	THREAD_CONTENT_MAX_LENGTH = 4 * 1024
	THREAD_TITLE_MAX_LENGTH   = 200
	THREAD_TITLE_MIN_LENGTH   = 5
	THREAD_LINK_MAX_LENGTH    = 255
	THREAD_LINKS_MAX_COUNT    = 1
	THREAD_KEYWORDS_MAX_COUNT = 5
	THREAD_KEYWORD_MAX_LENGTH = 30
	THREADS_LIST_COUNT        = 20
)
